package in.co.javacoder.oca.constructors.defaultnoarg;

public class Rabbit {

	public static void main(String[] args) {
		Rabbit rabbit = new Rabbit(); // calls default constructor
		
		// 1. Every java class has a constructor.
		// 2. It can be explicit or implicit one.
		// 3. If the programmer donot provide a constructor, the java compiler creates a constructor called default constructor with no arguments and with empty body.
		// 4. The default constructor looks like : public Rabbit() {}
		// 5. The default constructor will be generated if it is not provided.
		// 6. The default constructor will be generated by the compiler only if there is no constructor defined explicitly.
		//  Example : check Rabbit1 class
	}

}

